REM INSERTING into PERFORMANCE.BOOK1_AGE_LOG
SET DEFINE OFF;
Insert into PERFORMANCE.BOOK1_AGE_LOG (BOOK_ID,CHANGE_DATE,FROM_OLD_TO_NEW) values (4,to_date('25-DEC-23','DD-MON-RR'),'old age=21,new age=23');
