REM INSERTING into PERFORMANCE.CANDIDATE
SET DEFINE OFF;
Insert into PERFORMANCE.CANDIDATE (CANDIDATE_ID,FIRST_NAME,LAST_NAME,JOB_TITLE,YEAR_OF_EXPERIENCE) values (1,'Camila','Kramer','SCM Manager','+11 10:09:08.555000');
