REM INSERTING into PERFORMANCE.CUSTOMERS
SET DEFINE OFF;
Insert into PERFORMANCE.CUSTOMERS (CUSTOMER_ID,CREDIT_LIMIT) values (1,40);
Insert into PERFORMANCE.CUSTOMERS (CUSTOMER_ID,CREDIT_LIMIT) values (2,200);
Insert into PERFORMANCE.CUSTOMERS (CUSTOMER_ID,CREDIT_LIMIT) values (3,300);
Insert into PERFORMANCE.CUSTOMERS (CUSTOMER_ID,CREDIT_LIMIT) values (4,400);
Insert into PERFORMANCE.CUSTOMERS (CUSTOMER_ID,CREDIT_LIMIT) values (5,500);
