REM INSERTING into PERFORMANCE.DISCOUNT
SET DEFINE OFF;
Insert into PERFORMANCE.DISCOUNT (DIS_ID,NAME,PERCENTAGE,AMOUNT,ACTIVE_YN,CREATEDATE) values (1,'black friday        ',14,270,'y',to_date('09-JUN-13','DD-MON-RR'));
Insert into PERFORMANCE.DISCOUNT (DIS_ID,NAME,PERCENTAGE,AMOUNT,ACTIVE_YN,CREATEDATE) values (2,'black friday        ',14,270,'y',to_date('09-JUN-13','DD-MON-RR'));
Insert into PERFORMANCE.DISCOUNT (DIS_ID,NAME,PERCENTAGE,AMOUNT,ACTIVE_YN,CREATEDATE) values (3,'black friday        ',12,290,'n',to_date('09-JUN-12','DD-MON-RR'));
Insert into PERFORMANCE.DISCOUNT (DIS_ID,NAME,PERCENTAGE,AMOUNT,ACTIVE_YN,CREATEDATE) values (4,'black friday        ',50,255,'y',to_date('09-JUN-10','DD-MON-RR'));
Insert into PERFORMANCE.DISCOUNT (DIS_ID,NAME,PERCENTAGE,AMOUNT,ACTIVE_YN,CREATEDATE) values (5,'black friday        ',50,280,'y',to_date('11-MAR-16','DD-MON-RR'));
Insert into PERFORMANCE.DISCOUNT (DIS_ID,NAME,PERCENTAGE,AMOUNT,ACTIVE_YN,CREATEDATE) values (6,'black friday        ',22,250,'n',to_date('09-JUN-17','DD-MON-RR'));
Insert into PERFORMANCE.DISCOUNT (DIS_ID,NAME,PERCENTAGE,AMOUNT,ACTIVE_YN,CREATEDATE) values (7,'black friday        ',15,252,'y',to_date('15-JAN-19','DD-MON-RR'));
Insert into PERFORMANCE.DISCOUNT (DIS_ID,NAME,PERCENTAGE,AMOUNT,ACTIVE_YN,CREATEDATE) values (8,'black friday        ',52,270,'y',to_date('05-AUG-15','DD-MON-RR'));
