REM INSERTING into PERFORMANCE.MEMBER_STAGING
SET DEFINE OFF;
Insert into PERFORMANCE.MEMBER_STAGING (MEMBER_ID,FIRST_NAME,LAST_NAME,RANK) values (1,'Abel','Wolf','Silver');
Insert into PERFORMANCE.MEMBER_STAGING (MEMBER_ID,FIRST_NAME,LAST_NAME,RANK) values (2,'Clarita','Franco','Platinum');
Insert into PERFORMANCE.MEMBER_STAGING (MEMBER_ID,FIRST_NAME,LAST_NAME,RANK) values (3,'Darryl','Giles','Bronze');
Insert into PERFORMANCE.MEMBER_STAGING (MEMBER_ID,FIRST_NAME,LAST_NAME,RANK) values (4,'Dorthea','Suarez','Gold');
Insert into PERFORMANCE.MEMBER_STAGING (MEMBER_ID,FIRST_NAME,LAST_NAME,RANK) values (5,'Katrina','Wheeler','Silver');
Insert into PERFORMANCE.MEMBER_STAGING (MEMBER_ID,FIRST_NAME,LAST_NAME,RANK) values (6,'Lilian','Garza','Silver');
Insert into PERFORMANCE.MEMBER_STAGING (MEMBER_ID,FIRST_NAME,LAST_NAME,RANK) values (null,'Ossie','Summers',null);
Insert into PERFORMANCE.MEMBER_STAGING (MEMBER_ID,FIRST_NAME,LAST_NAME,RANK) values (null,'Paige','Mcfarland',null);
Insert into PERFORMANCE.MEMBER_STAGING (MEMBER_ID,FIRST_NAME,LAST_NAME,RANK) values (null,'Tressie','Short',null);
Insert into PERFORMANCE.MEMBER_STAGING (MEMBER_ID,FIRST_NAME,LAST_NAME,RANK) values (null,'Ronna','Britt',null);
